# Run settings
seed: 0
batch_size: 16

# Inputs
checkpoint_path: weights/fampnn_0_0.pt
out_dir: examples/outputs/pack

num_samples_per_pdb: 1
pdb_dir: null
pdb_key_list:
fixed_pos_csv: null  # Format: pdb_name, fix_seq_pos, fix_scn_pos. e.g. 2fyzA, "A1-100,B1-100", "A1-100". If pdb_name is not in the csv, no fixed positions are used.
fixed_pos_verbose: true

# Sidechain diffusion parameters
scn_diffusion:
  num_steps: 50
  timestep_schedule:
    num_steps: ${scn_diffusion.num_steps}
    mode: "linear"
    t_start: 0.0
    t_end: 1.0
  step_scale: 1.5
  churn_cfg:
    s_churn: 0
    s_noise: 1.0
    s_t_min: 0.01
    s_t_max: 50.0
    num_steps: ${scn_diffusion.num_steps}
